name: Prepare Database

on:
  push:
    branches:
      - deploy

jobs: 
  "setup-database":
    runs-on: cs5500-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Delete old database
        run: npm run remove_db.ts -- "mongodb://127.0.0.1:27017/my_library_db"

      - name: Seed database
        run: npm run insert_sample_data.ts -- "mongodb://127.0.0.1:27017/my_library_db"